"use client";

import { useTranslations, useLocale } from "next-intl";
import {
  Utensils,
  Scale,
  Droplets,
  Hash,
  Sparkles,
  Wrench,
  ShoppingCart,
  ArrowLeftRight,
  Pill,
  MoreHorizontal,
  Bot,
  User,
  AlertTriangle,
  Clock,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { CompleterActiviteDialog } from "@/components/planning/completer-activite-dialog";
import { FeedingRecommendation } from "@/components/activites/feeding-recommendation";
import { TypeActivite, StatutActivite, Permission, UniteStock } from "@/types";
import type { ActiviteWithRelations } from "@/types";
import { typeActiviteLabels } from "@/lib/labels/activite";

// ---------------------------------------------------------------------------
// Labels et icones par type d'activite
// ---------------------------------------------------------------------------

const typeActiviteIcons: Record<TypeActivite, React.ReactNode> = {
  [TypeActivite.ALIMENTATION]: <Utensils className="h-4 w-4" />,
  [TypeActivite.BIOMETRIE]: <Scale className="h-4 w-4" />,
  [TypeActivite.QUALITE_EAU]: <Droplets className="h-4 w-4" />,
  [TypeActivite.COMPTAGE]: <Hash className="h-4 w-4" />,
  [TypeActivite.NETTOYAGE]: <Sparkles className="h-4 w-4" />,
  [TypeActivite.TRAITEMENT]: <Wrench className="h-4 w-4" />,
  [TypeActivite.RECOLTE]: <ShoppingCart className="h-4 w-4" />,
  [TypeActivite.TRI]: <ArrowLeftRight className="h-4 w-4" />,
  [TypeActivite.MEDICATION]: <Pill className="h-4 w-4" />,
  [TypeActivite.RENOUVELLEMENT]: <Droplets className="h-4 w-4" />,
  [TypeActivite.AUTRE]: <MoreHorizontal className="h-4 w-4" />,
};


// ---------------------------------------------------------------------------
// Helpers priorite (1=basse, 2=moyenne, 3=critique)
// R6 : CSS variables du theme via classes Tailwind
// ---------------------------------------------------------------------------

interface PrioriteConfig {
  borderClass: string;
  iconBgClass: string;
  iconTextClass: string;
  badgeBgClass: string;
  badgeTextClass: string;
  dotClass: string;
}

function getPrioriteConfig(priorite: number): PrioriteConfig {
  if (priorite >= 3) {
    return {
      borderClass: "",
      iconBgClass: "bg-danger/10",
      iconTextClass: "text-danger",
      badgeBgClass: "bg-danger/10",
      badgeTextClass: "text-danger",
      dotClass: "bg-danger",
    };
  }
  if (priorite === 2) {
    return {
      borderClass: "",
      iconBgClass: "bg-warning/10",
      iconTextClass: "text-warning",
      badgeBgClass: "bg-warning/10",
      badgeTextClass: "text-warning",
      dotClass: "bg-warning",
    };
  }
  return {
    borderClass: "",
    iconBgClass: "bg-accent-blue/10",
    iconTextClass: "text-accent-blue",
    badgeBgClass: "bg-accent-blue/10",
    badgeTextClass: "text-accent-blue",
    dotClass: "bg-accent-blue",
  };
}

function getStatutBadgeVariant(
  statut: StatutActivite
): "default" | "en_cours" | "terminee" | "annulee" | "warning" {
  switch (statut) {
    case StatutActivite.PLANIFIEE:
      return "en_cours";
    case StatutActivite.TERMINEE:
      return "terminee";
    case StatutActivite.ANNULEE:
      return "annulee";
    case StatutActivite.EN_RETARD:
      return "default";
    default:
      return "default";
  }
}

// ---------------------------------------------------------------------------
// Composant ActiviteCard
// ---------------------------------------------------------------------------

export interface ActiviteCardProps {
  activite: ActiviteWithRelations;
  permissions: Permission[];
}

export function ActiviteCard({ activite, permissions }: ActiviteCardProps) {
  const t = useTranslations("activites");
  const tPlanning = useTranslations("planning");
  const locale = useLocale();

  const priorite = activite.priorite ?? 1;
  const config = getPrioriteConfig(priorite);
  const isEnRetard = activite.statut === StatutActivite.EN_RETARD;
  const isAutoGenerated = activite.isAutoGenerated;
  const typeActivite = activite.typeActivite as TypeActivite;
  const icon = typeActiviteIcons[typeActivite] ?? <MoreHorizontal className="h-4 w-4" />;
  const typeLabel = typeActiviteLabels[typeActivite] ?? activite.typeActivite;

  function getPrioriteLabel(): string {
    if (priorite >= 3) return t("filters.priorities.URGENTE");
    if (priorite === 2) return t("filters.priorities.MOYENNE");
    return t("filters.priorities.BASSE");
  }

  function getStatutLabel(statut: StatutActivite): string {
    switch (statut) {
      case StatutActivite.PLANIFIEE:
        return tPlanning("statuts.PLANIFIEE");
      case StatutActivite.TERMINEE:
        return tPlanning("statuts.TERMINEE");
      case StatutActivite.ANNULEE:
        return tPlanning("statuts.ANNULEE");
      case StatutActivite.EN_RETARD:
        return t("statuses.late");
      default:
        return statut;
    }
  }

  const canComplete =
    permissions.includes(Permission.PLANNING_GERER) &&
    (activite.statut === StatutActivite.PLANIFIEE ||
      activite.statut === StatutActivite.EN_RETARD);

  return (
    <div
      className={[
        "rounded-xl border bg-card p-4 transition-all",
        config.borderClass,
        isEnRetard ? "bg-danger/5" : "",
      ]
        .filter(Boolean)
        .join(" ")}
    >
      {/* Header : icone + titre + badge statut */}
      <div className="flex items-start justify-between gap-2 mb-2">
        <div className="flex items-start gap-2.5 min-w-0">
          {/* Icone type avec couleur priorite */}
          <div
            className={[
              "mt-0.5 shrink-0 rounded-md p-1.5",
              config.iconBgClass,
              config.iconTextClass,
            ].join(" ")}
          >
            {icon}
          </div>
          <div className="min-w-0">
            <p className="font-medium text-sm leading-tight line-clamp-2">
              {activite.titre}
            </p>
          </div>
        </div>

        {/* Badge statut */}
        <Badge
          variant={getStatutBadgeVariant(activite.statut as StatutActivite)}
          className="shrink-0"
        >
          {isEnRetard && (
            <AlertTriangle className="h-3 w-3 mr-1 inline-block" />
          )}
          {getStatutLabel(activite.statut as StatutActivite)}
        </Badge>
      </div>

      {/* Metadata : type, vague, bac */}
      <div className="flex flex-wrap items-center gap-1.5 text-xs text-muted-foreground mb-2">
        <span>{typeLabel}</span>
        {activite.vague && (
          <>
            <span className="text-muted-foreground/40">·</span>
            <span>{activite.vague.code}</span>
          </>
        )}
        {activite.bac && (
          <>
            <span className="text-muted-foreground/40">·</span>
            <span>{activite.bac.nom}</span>
          </>
        )}
      </div>

      {/* Badge phase d'elevage (si auto-generee et phase connue) */}
      {activite.phaseElevage && (
        <div className="mb-2">
          <span className="inline-flex items-center gap-1 rounded-full bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">
            {t(`phases.${activite.phaseElevage}` as Parameters<typeof t>[0]) ??
              activite.phaseElevage}
          </span>
        </div>
      )}

      {/* Pied de carte : date + badges + bouton completer */}
      <div className="flex flex-wrap items-center justify-between gap-2 mt-2">
        <div className="flex flex-wrap items-center gap-2">
          {/* Date */}
          <span className="flex items-center gap-1 text-xs text-muted-foreground">
            <Clock className="h-3 w-3" />
            {new Date(activite.dateDebut).toLocaleDateString(locale, {
              weekday: "short",
              day: "numeric",
              month: "short",
              hour: "2-digit",
              minute: "2-digit",
            })}
          </span>

          {/* Badge auto-genere vs manuel */}
          {isAutoGenerated ? (
            <span className="inline-flex items-center gap-1 rounded-full bg-accent-purple/10 px-2 py-0.5 text-xs text-accent-purple">
              <Bot className="h-3 w-3" />
              Auto
            </span>
          ) : (
            <span className="inline-flex items-center gap-1 rounded-full bg-muted px-2 py-0.5 text-xs text-muted-foreground">
              <User className="h-3 w-3" />
              Manuelle
            </span>
          )}

          {/* Badge priorite */}
          <span
            className={[
              "inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium",
              config.badgeBgClass,
              config.badgeTextClass,
            ].join(" ")}
          >
            <span
              className={["h-1.5 w-1.5 rounded-full", config.dotClass].join(
                " "
              )}
            />
            {getPrioriteLabel()}
          </span>
        </div>

        {/* Bouton completer */}
        {canComplete && (
          <div className="shrink-0">
            <CompleterActiviteDialog activite={activite} />
          </div>
        )}
      </div>

      {/* Instructions detaillees (si auto-generee) */}
      {activite.instructionsDetaillees && (
        <div className="mt-3 rounded-lg bg-muted/50 px-3 py-2">
          <p className="text-xs text-muted-foreground leading-relaxed">
            {activite.instructionsDetaillees}
          </p>
        </div>
      )}

      {/* Conseil IA */}
      {activite.conseilIA && (
        <div className="mt-2 rounded-lg bg-warning/10 px-3 py-2">
          <p className="text-xs text-warning leading-relaxed">
            {activite.conseilIA}
          </p>
        </div>
      )}

      {/* Recommandation d'alimentation (S16-4) — uniquement pour TypeActivite.ALIMENTATION */}
      {typeActivite === TypeActivite.ALIMENTATION &&
        activite.quantiteRecommandee != null && (
          <FeedingRecommendation
            quantiteRecommandee={activite.quantiteRecommandee}
            tailleGranule={null}
            frequence={null}
            phaseElevage={activite.phaseElevage}
            poidsMoyenUtilise={null}
            nombreVivantsUtilise={null}
            estProjete={false}
            produitStock={
              activite.produitRecommande != null
                ? {
                    id: activite.produitRecommande.id,
                    nom: activite.produitRecommande.nom,
                    unite: activite.produitRecommande.unite as UniteStock,
                    stockActuel: activite.produitRecommande.stockActuel,
                    uniteAchat: activite.produitRecommande.uniteAchat as UniteStock | null,
                    contenance: activite.produitRecommande.contenance,
                  }
                : null
            }
            parBac={null}
          />
        )}
    </div>
  );
}
