-- Migration R1-S1 — Module Reproduction : 12 nouveaux enums
-- CreateEnum
CREATE TYPE "ModeGestionGeniteur" AS ENUM ('GROUPE', 'INDIVIDUEL');

-- CreateEnum
CREATE TYPE "GenerationGeniteur" AS ENUM ('G0_SAUVAGE', 'G1', 'G2', 'G3_PLUS', 'INCONNUE');

-- CreateEnum
CREATE TYPE "SourcingGeniteur" AS ENUM ('PROPRE_PRODUCTION', 'ACHAT_FERMIER', 'SAUVAGE', 'STATION_RECHERCHE');

-- CreateEnum
CREATE TYPE "TypeHormone" AS ENUM ('OVAPRIM', 'OVATIDE', 'HCG', 'HYPOPHYSE_SILURE', 'HYPOPHYSE_CARPE', 'HYPOPHYSE_TILAPIA', 'LHRH_A', 'AUTRE');

-- CreateEnum
CREATE TYPE "QualiteOeufs" AS ENUM ('EXCELLENTE', 'BONNE', 'MOYENNE', 'MAUVAISE', 'NON_EVALUEE');

-- CreateEnum
CREATE TYPE "MethodeExtractionMale" AS ENUM ('SACRIFICE', 'CHIRURGICALE');

-- CreateEnum
CREATE TYPE "MotiliteSperme" AS ENUM ('OK', 'KO', 'NON_TESTE');

-- CreateEnum
CREATE TYPE "CauseEchecPonte" AS ENUM ('STRIPPING_TROP_PRECOCE', 'STRIPPING_TROP_TARDIF', 'SPERME_NON_VIABLE', 'CONTAMINATION_EAU', 'FEMELLE_NON_MATURE', 'HORMONE_INSUFFISANTE', 'TEMPERATURE_INADAPTEE', 'MANIPULATION_EXCESSIVE', 'AUTRE');

-- CreateEnum
CREATE TYPE "SubstratIncubation" AS ENUM ('RACINES_PISTIA', 'JACINTHES_EAU', 'PLATEAU_PERFORE', 'EPONGE_PONTE', 'BROSSES_FLOTTANTES', 'KAKABAN', 'FOND_BETON', 'AUTRE');

-- CreateEnum
CREATE TYPE "StatutIncubation" AS ENUM ('EN_COURS', 'ECLOSION_EN_COURS', 'TERMINEE', 'ECHOUEE');

-- CreateEnum
CREATE TYPE "PhaseLot" AS ENUM ('INCUBATION', 'LARVAIRE', 'NURSERIE', 'ALEVINAGE', 'SORTI', 'PERDU');

-- CreateEnum
CREATE TYPE "DestinationLot" AS ENUM ('VENTE_ALEVINS', 'TRANSFERT_GROSSISSEMENT', 'TRANSFERT_INTERNE', 'REFORMAGE');
