import { Permission } from "@/types";

export const groupLabels: Record<string, string> = {
  administration: "Administration",
  elevage: "Elevage",
  stock: "Stock & Approvisionnement",
  clients: "Clients",
  ventes: "Ventes & Facturation",
  alevins: "Production Alevins",
  planning: "Planning",
  finances: "Finances",
  alertes: "Alertes",
  depenses: "Depenses & Besoins",
  general: "General",
  packs: "Packs & Provisioning",
  configElevage: "Configuration Elevage",
  ingenieur: "Ingenieur",
};

export const permissionLabels: Record<string, string> = {
  [Permission.SITE_GERER]: "Gerer le site",
  [Permission.MEMBRES_GERER]: "Gerer les membres",
  [Permission.VAGUES_VOIR]: "Voir les vagues",
  [Permission.VAGUES_CREER]: "Creer des vagues",
  [Permission.VAGUES_MODIFIER]: "Modifier les vagues",
  [Permission.BACS_GERER]: "Gerer les bacs",
  [Permission.BACS_MODIFIER]: "Modifier les bacs",
  [Permission.RELEVES_VOIR]: "Voir les releves",
  [Permission.RELEVES_CREER]: "Creer des releves",
  [Permission.RELEVES_MODIFIER]: "Modifier les releves",
  [Permission.STOCK_VOIR]: "Voir le stock",
  [Permission.STOCK_GERER]: "Gerer le stock",
  [Permission.APPROVISIONNEMENT_VOIR]: "Voir approvisionnement",
  [Permission.APPROVISIONNEMENT_GERER]: "Gerer approvisionnement",
  [Permission.CLIENTS_VOIR]: "Voir les clients",
  [Permission.CLIENTS_GERER]: "Gerer les clients",
  [Permission.VENTES_VOIR]: "Voir les ventes",
  [Permission.VENTES_CREER]: "Creer des ventes",
  [Permission.FACTURES_VOIR]: "Voir les factures",
  [Permission.FACTURES_GERER]: "Gerer les factures",
  [Permission.PAIEMENTS_CREER]: "Enregistrer des paiements",
  [Permission.ALEVINS_VOIR]: "Voir les alevins",
  [Permission.ALEVINS_CREER]: "Creer des lots d'alevins",
  [Permission.ALEVINS_MODIFIER]: "Modifier les alevins",
  [Permission.ALEVINS_SUPPRIMER]: "Supprimer des alevins",
  [Permission.ALEVINS_GERER]: "Gerer les alevins",
  [Permission.PLANNING_VOIR]: "Voir le planning",
  [Permission.PLANNING_GERER]: "Gerer le planning",
  [Permission.FINANCES_VOIR]: "Voir les finances",
  [Permission.FINANCES_GERER]: "Gerer les finances",
  [Permission.ALERTES_CONFIGURER]: "Configurer les alertes",
  [Permission.DASHBOARD_VOIR]: "Voir le dashboard",
  [Permission.ALERTES_VOIR]: "Voir les alertes",
  [Permission.EXPORT_DONNEES]: "Exporter les donnees",
  // Phase 3
  [Permission.GERER_PACKS]: "Gerer les packs",
  [Permission.ACTIVER_PACKS]: "Activer les packs",
  [Permission.GERER_CONFIG_ELEVAGE]: "Gerer la configuration d'elevage",
  [Permission.REGLES_ACTIVITES_VOIR]: "Voir les regles d'activites",
  [Permission.GERER_REGLES_ACTIVITES]: "Gerer les regles d'activites",
  [Permission.MONITORING_CLIENTS]: "Monitoring clients",
  [Permission.ENVOYER_NOTES]: "Envoyer des notes",
  [Permission.CALIBRAGES_VOIR]: "Voir les calibrages",
  [Permission.CALIBRAGES_CREER]: "Creer des calibrages",
  [Permission.DEPENSES_VOIR]: "Voir les depenses",
  [Permission.DEPENSES_CREER]: "Creer des depenses",
  [Permission.DEPENSES_PAYER]: "Payer les depenses",
  [Permission.BESOINS_SOUMETTRE]: "Soumettre des besoins",
  [Permission.BESOINS_APPROUVER]: "Approuver des besoins",
  [Permission.BESOINS_TRAITER]: "Traiter des besoins",
};
