services:
  db:
    image: postgres:16-alpine
    container_name: silures-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dkfarm
      POSTGRES_PASSWORD: "@DkFarm2026!"
      POSTGRES_DB: farm-flow
    ports:
      - "8432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
