-- Sprint 21 — Moteur d'activités automatiques
-- Ajoute : TypeDeclencheur enum, RegleActivite model,
--          enrichissement Activite (8 nouveaux champs),
--          et complète les enums Permission + TypeActivite (Sprint 20 non appliqué)

-- CreateEnum
CREATE TYPE "TypeDeclencheur" AS ENUM ('CALENDRIER', 'RECURRENT', 'SEUIL_POIDS', 'SEUIL_QUALITE', 'SEUIL_MORTALITE', 'STOCK_BAS', 'FCR_ELEVE', 'JALON');

-- AlterEnum: Permission — nouvelles valeurs Phase 3 Packs & Ingénieur
ALTER TYPE "Permission" ADD VALUE 'GERER_PACKS';
ALTER TYPE "Permission" ADD VALUE 'ACTIVER_PACKS';
ALTER TYPE "Permission" ADD VALUE 'GERER_CONFIG_ELEVAGE';
ALTER TYPE "Permission" ADD VALUE 'GERER_REGLES_ACTIVITES';
ALTER TYPE "Permission" ADD VALUE 'MONITORING_CLIENTS';
ALTER TYPE "Permission" ADD VALUE 'ENVOYER_NOTES';

-- AlterEnum: TypeActivite — nouvelles valeurs TRI + MEDICATION
ALTER TYPE "TypeActivite" ADD VALUE 'TRI';
ALTER TYPE "TypeActivite" ADD VALUE 'MEDICATION';

-- AlterTable: Activite — 8 nouveaux champs Sprint 21
ALTER TABLE "Activite"
  ADD COLUMN "regleId"                TEXT,
  ADD COLUMN "instructionsDetaillees" TEXT,
  ADD COLUMN "conseilIA"              TEXT,
  ADD COLUMN "produitRecommandeId"    TEXT,
  ADD COLUMN "quantiteRecommandee"    DOUBLE PRECISION,
  ADD COLUMN "priorite"               INTEGER,
  ADD COLUMN "isAutoGenerated"        BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "phaseElevage"           "PhaseElevage";

-- CreateTable: RegleActivite
CREATE TABLE "RegleActivite" (
    "id"                   TEXT NOT NULL,
    "nom"                  TEXT NOT NULL,
    "description"          TEXT,
    "typeActivite"         "TypeActivite" NOT NULL,
    "typeDeclencheur"      "TypeDeclencheur" NOT NULL,
    "conditionValeur"      DOUBLE PRECISION,
    "conditionValeur2"     DOUBLE PRECISION,
    "phaseMin"             "PhaseElevage",
    "phaseMax"             "PhaseElevage",
    "intervalleJours"      INTEGER,
    "titreTemplate"        TEXT NOT NULL,
    "descriptionTemplate"  TEXT,
    "instructionsTemplate" TEXT,
    "priorite"             INTEGER NOT NULL DEFAULT 5,
    "isActive"             BOOLEAN NOT NULL DEFAULT true,
    "firedOnce"            BOOLEAN NOT NULL DEFAULT false,
    "siteId"               TEXT,
    "userId"               TEXT,
    "createdAt"            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"            TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RegleActivite_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "RegleActivite_siteId_idx" ON "RegleActivite"("siteId");
CREATE INDEX "RegleActivite_typeActivite_idx" ON "RegleActivite"("typeActivite");
CREATE INDEX "RegleActivite_typeDeclencheur_idx" ON "RegleActivite"("typeDeclencheur");
CREATE INDEX "RegleActivite_isActive_idx" ON "RegleActivite"("isActive");

-- CreateIndex on Activite
CREATE INDEX "Activite_regleId_idx" ON "Activite"("regleId");
CREATE INDEX "Activite_isAutoGenerated_idx" ON "Activite"("isAutoGenerated");

-- AddForeignKey: Activite.regleId → RegleActivite
ALTER TABLE "Activite"
  ADD CONSTRAINT "Activite_regleId_fkey"
  FOREIGN KEY ("regleId") REFERENCES "RegleActivite"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey: Activite.produitRecommandeId → Produit
ALTER TABLE "Activite"
  ADD CONSTRAINT "Activite_produitRecommandeId_fkey"
  FOREIGN KEY ("produitRecommandeId") REFERENCES "Produit"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey: RegleActivite.siteId → Site (nullable = règle globale F-15)
ALTER TABLE "RegleActivite"
  ADD CONSTRAINT "RegleActivite_siteId_fkey"
  FOREIGN KEY ("siteId") REFERENCES "Site"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey: RegleActivite.userId → User
ALTER TABLE "RegleActivite"
  ADD CONSTRAINT "RegleActivite_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;
