-- Sprint 21 — Moteur d'activités automatiques
-- Ajoute : TypeDeclencheur enum, RegleActivite model,
--          enrichissement Activite (8 nouveaux champs)
-- NOTE: Made idempotent because a prior partial run created TypeDeclencheur

-- CreateEnum (idempotent — may already exist from prior failed run)
DO $$ BEGIN
  CREATE TYPE "TypeDeclencheur" AS ENUM ('CALENDRIER', 'RECURRENT', 'SEUIL_POIDS', 'SEUIL_QUALITE', 'SEUIL_MORTALITE', 'STOCK_BAS', 'FCR_ELEVE', 'JALON');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- AlterTable: Activite — 8 nouveaux champs Sprint 21
ALTER TABLE "Activite"
  ADD COLUMN IF NOT EXISTS "regleId"                TEXT,
  ADD COLUMN IF NOT EXISTS "instructionsDetaillees" TEXT,
  ADD COLUMN IF NOT EXISTS "conseilIA"              TEXT,
  ADD COLUMN IF NOT EXISTS "produitRecommandeId"    TEXT,
  ADD COLUMN IF NOT EXISTS "quantiteRecommandee"    DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "priorite"               INTEGER,
  ADD COLUMN IF NOT EXISTS "isAutoGenerated"        BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "phaseElevage"           "PhaseElevage";

-- CreateTable: RegleActivite
CREATE TABLE IF NOT EXISTS "RegleActivite" (
    "id"                   TEXT NOT NULL,
    "nom"                  TEXT NOT NULL,
    "description"          TEXT,
    "typeActivite"         "TypeActivite" NOT NULL,
    "typeDeclencheur"      "TypeDeclencheur" NOT NULL,
    "conditionValeur"      DOUBLE PRECISION,
    "conditionValeur2"     DOUBLE PRECISION,
    "phaseMin"             "PhaseElevage",
    "phaseMax"             "PhaseElevage",
    "intervalleJours"      INTEGER,
    "titreTemplate"        TEXT NOT NULL,
    "descriptionTemplate"  TEXT,
    "instructionsTemplate" TEXT,
    "priorite"             INTEGER NOT NULL DEFAULT 5,
    "isActive"             BOOLEAN NOT NULL DEFAULT true,
    "firedOnce"            BOOLEAN NOT NULL DEFAULT false,
    "siteId"               TEXT,
    "userId"               TEXT,
    "createdAt"            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"            TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RegleActivite_pkey" PRIMARY KEY ("id")
);

-- CreateIndex (idempotent)
CREATE INDEX IF NOT EXISTS "RegleActivite_siteId_idx" ON "RegleActivite"("siteId");
CREATE INDEX IF NOT EXISTS "RegleActivite_typeActivite_idx" ON "RegleActivite"("typeActivite");
CREATE INDEX IF NOT EXISTS "RegleActivite_typeDeclencheur_idx" ON "RegleActivite"("typeDeclencheur");
CREATE INDEX IF NOT EXISTS "RegleActivite_isActive_idx" ON "RegleActivite"("isActive");

-- CreateIndex on Activite
CREATE INDEX IF NOT EXISTS "Activite_regleId_idx" ON "Activite"("regleId");
CREATE INDEX IF NOT EXISTS "Activite_isAutoGenerated_idx" ON "Activite"("isAutoGenerated");

-- AddForeignKey: Activite.regleId → RegleActivite
DO $$ BEGIN
  ALTER TABLE "Activite"
    ADD CONSTRAINT "Activite_regleId_fkey"
    FOREIGN KEY ("regleId") REFERENCES "RegleActivite"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- AddForeignKey: Activite.produitRecommandeId → Produit
DO $$ BEGIN
  ALTER TABLE "Activite"
    ADD CONSTRAINT "Activite_produitRecommandeId_fkey"
    FOREIGN KEY ("produitRecommandeId") REFERENCES "Produit"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- AddForeignKey: RegleActivite.siteId → Site (nullable = règle globale F-15)
DO $$ BEGIN
  ALTER TABLE "RegleActivite"
    ADD CONSTRAINT "RegleActivite_siteId_fkey"
    FOREIGN KEY ("siteId") REFERENCES "Site"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- AddForeignKey: RegleActivite.userId → User
DO $$ BEGIN
  ALTER TABLE "RegleActivite"
    ADD CONSTRAINT "RegleActivite_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
