/**
 * Garde-fou anti-récidive — Story MG.6 (ADR-049 / ADR-050).
 *
 * Contexte : quatre correctifs de données de production ont été commités à la
 * RACINE de `prisma/migrations/` (commit `c259b48`) — `fix-vague2601-phantom-fish.sql`,
 * `fix-bes033-cmd015-duplicate.sql`, `fix-calibrage-may14-missing-biometrie.sql`,
 * `fix-vte004-missing-vagueid.sql`. Prisma ne lit comme migration que les
 * SOUS-DOSSIERS de `prisma/migrations/` contenant un `migration.sql` — ces
 * quatre fichiers étaient donc totalement INERTES : jamais exécutés par
 * `migrate deploy`, jamais enregistrés dans `_prisma_migrations`, sans aucune
 * garantie sur leur application réelle en production (voir ADR-049 §1).
 *
 * Ce fichier verrouille deux invariants distincts :
 *
 *   (a) Aucun fichier ne doit jamais réapparaître à la racine de
 *       `prisma/migrations/` (le bug exact de commit `c259b48`) — vérification
 *       structurelle triviale, sans ambiguïté possible.
 *   (b) Aucun correctif de données à écriture ne doit être ajouté sous forme
 *       de script `.sql`/`.sh` hors du mécanisme de migration — il ne peut
 *       s'agir que d'un audit en lecture seule (ADR-050 : emplacement
 *       `scripts/audits/` + convention de nommage `*-audit-*`).
 *
 * Choix de mécanisme pour (b) — DÉLIBÉRÉMENT PAS une heuristique de mots-clés
 * SQL naïve. La pré-analyse (section F) et ADR-049 §4 rejettent explicitement
 * une détection par regex de contenu (`UPDATE`/`INSERT`/`DELETE` en clair) car
 * un commentaire mentionnant le mot "UPDATE" ne fait pas d'un fichier un
 * correctif, et l'absence de ces mots-clés ne prouve pas qu'un fichier est un
 * audit. Le critère RETENU est donc, par ordre de priorité :
 *   1. Propriété de CHEMIN + NOMMAGE (ADR-050) : un fichier n'est un audit
 *      légitime QUE s'il vit sous `scripts/audits/` ET porte `-audit-` dans
 *      son nom. C'est une propriété du système de fichiers, déterministe,
 *      jamais devinatoire.
 *   2. Pour les fichiers déclarés "audit" par (1), une détection de mots-clés
 *      d'écriture SQL (UPDATE/INSERT/DELETE/ALTER/DROP/TRUNCATE) est utilisée
 *      UNIQUEMENT comme signal de COHÉRENCE (pas comme critère de
 *      qualification) — et seulement HORS des commentaires SQL (`--` et
 *      `/* *\/`), pour éviter un faux positif sur un commentaire qui
 *      mentionnerait ces mots (cf. prose ci-dessus). Si ce signal se
 *      déclenche, il indique une INCOHÉRENCE entre le nommage et le contenu
 *      réel — qui doit être investiguée, pas un verdict automatique de rejet
 *      du fichier par le mécanisme (1).
 *   3. Tout fichier `.sql`/`.sh` sous `scripts/` ou `prisma/` qui n'est ni une
 *      migration légitime (`prisma/migrations/<dossier>/migration.sql`) ni un
 *      audit qualifié par (1) est une VIOLATION — sauf s'il figure dans la
 *      liste de dette historique explicite ci-dessous.
 *
 * Dette historique tolérée (voir détail et justification individuelle plus
 * bas) : neuf fichiers de correctif orphelins antérieurs à ADR-049, dont
 * l'état d'application réel en production est inconnu — on ne les convertit
 * PAS à l'aveugle (MG.3 ne couvre que les 5 correctifs nommément analysés par
 * MG.2 : vague2601, bes033/cmd015, calibrage-may14, vte004, gd3 — tous les 5
 * ont déjà été convertis en migrations, cf. `prisma/migrations/20260727090001..006`).
 * Cette liste est fermée : toute NOUVELLE violation qui n'y figure pas fait
 * échouer le test.
 */

import { describe, it, expect } from "vitest";
import { readdirSync, existsSync, readFileSync, type Dirent } from "node:fs";
import path from "node:path";

const REPO_ROOT = process.cwd();
const MIGRATIONS_DIR = path.join(REPO_ROOT, "prisma/migrations");

// ---------------------------------------------------------------------------
// (a) Aucun fichier .sql (ni aucun fichier tout court, hors exception nommée)
//     à la racine de prisma/migrations/.
// ---------------------------------------------------------------------------

/**
 * Seule exception légitime : `migration_lock.toml` est déposé par Prisma
 * lui-même (pas par un agent humain) pour verrouiller le provider de
 * datasource ("Please do not edit this file manually" — commentaire généré
 * par Prisma en tête du fichier). Ce n'est pas un correctif de données, pas
 * un script exécutable, et Prisma le régénère de toute façon s'il est
 * supprimé — l'exclure ici ne rouvre aucune porte au bug de commit `c259b48`.
 */
const MIGRATION_LOCK_FILE = "migration_lock.toml";

/** Fonction pure — extraite pour être testable sur des Dirent fabriqués. */
export function findIllegalFilesAtMigrationsRoot(
  entries: Array<Pick<Dirent, "name"> & { isFile(): boolean }>
): string[] {
  return entries
    .filter((e) => e.isFile() && e.name !== MIGRATION_LOCK_FILE)
    .map((e) => e.name);
}

// ---------------------------------------------------------------------------
// (b) Aucun correctif de données à écriture hors du mécanisme de migration.
// ---------------------------------------------------------------------------

/**
 * Une migration légitime : tout fichier vivant DIRECTEMENT dans un dossier
 * `prisma/migrations/<dossier>/` (profondeur exacte 2, pas plus, pas moins).
 * Pas seulement `migration.sql` : un dossier de migration peut légitimement
 * contenir un fichier compagnon comme `rollback.sql`
 * (`prisma/migrations/20260404000000_add_feed_analytics/rollback.sql`) — ce
 * n'est ni un correctif de données orphelin, ni un audit, c'est un artefact
 * du même mécanisme de migration que `migration.sql`, review porté par le
 * dossier timestampé lui-même. La règle (b) vise les scripts qui vivent HORS
 * de ce mécanisme, pas les compagnons DDL/rollback qui vivent DEDANS.
 */
export function isLegitimateMigrationFile(relPath: string): boolean {
  return /^prisma\/migrations\/[^/]+\/[^/]+$/.test(relPath);
}

/**
 * Fichiers connus, permanents, qui ne sont PAS des correctifs de données et
 * ne relèvent donc pas de la dette historique (ce ne sont pas des candidats
 * à une conversion en migration un jour) : `prisma/seed.sql` est le seed
 * canonique du projet (dev/test), exécuté via `npm run db:seed` — une
 * convention établie et documentée (ERR-003), pas un correctif de production.
 *
 * `scripts/typecheck-budget.sh` (sprint de résorption des réserves du module
 * Prévisions, réserve R6) : garde-fou de CI qui lance `npx tsc --noEmit` et
 * compare le compte d'erreurs à un seuil versionné (`typecheck-budget.txt`).
 * Aucune écriture de données, aucune requête SQL, aucune connexion DB — ce
 * n'est structurellement pas un correctif au sens ADR-049 (rien à convertir
 * en migration un jour), simplement un outil de développement qui se trouve
 * être un `.sh` sous `scripts/`, la même situation que `prisma/seed.sql` pour
 * les `.sql`.
 */
const KNOWN_NON_DATAFIX_FILES = new Set<string>([
  "prisma/seed.sql",
  "scripts/typecheck-budget.sh",
]);

/**
 * Un audit qualifié au sens ADR-050 : sous scripts/audits/, ET le nom de
 * fichier (pas le chemin complet) contient la chaîne "-audit-".
 */
export function isQualifiedAuditPath(relPath: string): boolean {
  if (!relPath.startsWith("scripts/audits/")) return false;
  const filename = relPath.split("/").pop() ?? "";
  return filename.includes("-audit-");
}

/**
 * Retire les commentaires SQL (`-- ligne` et `/* bloc *\/`) d'un contenu, pour
 * que la détection de mots-clés d'écriture ne se déclenche jamais sur un
 * commentaire qui mentionnerait ces mots en prose (cf. en-tête du fichier).
 * Volontairement simple (pas de gestion des littéraux de chaîne contenant
 * "--" ou "/*") : ce mécanisme n'est qu'un SIGNAL DE COHÉRENCE sur des
 * fichiers déjà qualifiés "audit" par le chemin, jamais un critère de
 * qualification à lui seul — une sur-ingénierie ici serait hors de
 * proportion avec son rôle réel.
 */
export function stripSqlComments(sql: string): string {
  return sql
    .replace(/\/\*[\s\S]*?\*\//g, " ")
    .split("\n")
    .map((line) => {
      const idx = line.indexOf("--");
      return idx === -1 ? line : line.slice(0, idx);
    })
    .join("\n");
}

const WRITE_KEYWORDS = /\b(UPDATE|INSERT|DELETE|ALTER|DROP|TRUNCATE|CREATE)\b/i;

/**
 * Signal de cohérence (pas un critère de qualification) : un fichier déclaré
 * "audit" par son chemin/nommage ne devrait contenir aucun mot-clé d'écriture
 * SQL hors commentaire. Utilisé uniquement à titre de garde complémentaire —
 * voir la note d'en-tête sur l'ordre de priorité des mécanismes.
 */
export function auditFileHasWriteKeywordOutsideComments(sqlContent: string): boolean {
  return WRITE_KEYWORDS.test(stripSqlComments(sqlContent));
}

/**
 * Dette historique tolérée — chaque entrée DOIT porter un motif écrit
 * (pattern déjà utilisé par `permissions-orphan-guard.test.ts`). Cette liste
 * est fermée : elle ne doit JAMAIS grossir silencieusement. Toute nouvelle
 * violation hors de cette liste précise fait échouer le test.
 *
 * Groupe 1 — les 4 correctifs cités explicitement par la mission MG.6 et par
 * la pré-analyse (section A/F) : orphelins découverts en parallèle des 5
 * correctifs traités par MG.2/MG.3 (ceux-là ont bien été convertis en
 * migrations, cf. `prisma/migrations/20260727090001..006` — ils n'apparaissent
 * donc plus dans l'arbre du dépôt et n'ont pas besoin d'exclusion).
 *
 * Groupe 2 — cinq correctifs supplémentaires découverts pendant l'écriture de
 * CE garde-fou (grep exhaustif de `prisma/data-fixes/`, non mentionnés par la
 * mission MG.6 ni par la pré-analyse) : ils mêlent une section SELECT
 * d'audit et une section UPDATE/INSERT conditionnelle, documentée comme
 * nécessitant une revue manuelle avant exécution — donc clairement des
 * correctifs de données au sens ADR-049 §3.1 ("un script qui ne fait qu'un
 * SELECT pour vérifier, puis un UPDATE conditionnel juste après, est un
 * correctif de données dans son intégralité"), pas des audits purs. Ne pas
 * les inclure dans cette dette aurait fait échouer ce test dès son
 * introduction (violation du critère "zéro faux positif sur l'état actuel
 * du dépôt") — mais leur conversion en migration idempotente est HORS
 * PÉRIMÈTRE de MG.6 (seuls les 5 correctifs analysés par MG.2 ont été
 * convertis) : leur état d'application réel en production n'a pas été établi
 * par ce sprint, donc on ne les convertit pas à l'aveugle, exactement pour
 * la même raison que le groupe 1.
 */
const HISTORICAL_DEBT_EXCLUSIONS: Record<string, string> = {
  "prisma/fix-vague-26-01.sql":
    "Antérieur à ADR-049 (Fix 6, sans date explicite en en-tête, présent au moins depuis le 2 avril 2026). " +
    "Correctif UPDATE unique sur Vague.nombreInitial, déjà idempotent en l'état (WHERE ... != valeur cible) " +
    "mais jamais converti en migration Prisma. État d'application en prod inconnu depuis le dépôt — " +
    "hors périmètre de conversion de MG.3 (seuls les 5 correctifs analysés par MG.2 l'ont été). " +
    "Ne pas convertir à l'aveugle ni supprimer sans confirmation de l'état réel de la base cible.",
  "scripts/fix-missing-mouvements.sql":
    "Script de correction production du 2026-05-18 (3 corrections : suppression de LigneDepense " +
    "doublons, recalcul de montantTotal, création de MouvementStock manquants). Antérieur à ADR-049, " +
    "hors périmètre de conversion de MG.3. État d'application en prod inconnu depuis le dépôt.",
  "scripts/fix-depense-mouvement-link.sql":
    "Script de correction production du 2026-05-18 (liaison Depense <-> MouvementStock, création de " +
    "dépenses manquantes pour combler un écart de 328 500 F). Antérieur à ADR-049, hors périmètre de " +
    "conversion de MG.3. État d'application en prod inconnu depuis le dépôt.",
  "scripts/repair-bug041.sql":
    "Correctif BUG-041 (backfill AssignationBac pour les vagues créées avant le fix POST /api/vagues). " +
    "INSERT protégé par un NOT EXISTS (idempotent), mais jamais converti en migration Prisma. Antérieur " +
    "à ADR-049, hors périmètre de conversion de MG.3. État d'application en prod inconnu depuis le dépôt.",
  "prisma/data-fixes/CG2-bacdest-null.sql":
    "Sprint CG (Conservation Garantie), story CG.2, daté 2026-06-11 : réparation de TransfertGroupe.bacDestId " +
    "NULL. Contient une section SELECT d'audit ET une section UPDATE explicitement conditionnée à une " +
    "'revue manuelle des candidats' avant exécution — un correctif de données au sens ADR-049 §3.1, pas un " +
    "audit pur, découvert pendant l'écriture de ce garde-fou (non listé par la mission MG.6 ni la " +
    "pré-analyse). Hors périmètre de conversion de MG.3 — état d'application réel non établi par ce sprint.",
  "prisma/data-fixes/CG4-assignation-dates.sql":
    "Sprint CG, story CG.4, daté 2026-06-11 : correction des dates AssignationBac désynchronisées de " +
    "l'opération métier parente (calibrage/transfert/arrivage, cf. incident Bac 11). Section SELECT d'audit " +
    "suivie de sections UPDATE à décommenter manuellement après relecture — correctif de données, pas un " +
    "audit pur. Découvert pendant l'écriture de ce garde-fou. Hors périmètre de conversion de MG.3.",
  "prisma/data-fixes/CS1-init-fields-prod.sql":
    "Sprint CS.1, daté 2026-06-11 : recalcul de nombreInitial/poidsMoyenInitial sur AssignationBac " +
    "destination (créés à 0 par un bug de createTransfert/updateTransfertGroupe). SECTION 1 = audit SELECT, " +
    "SECTION 2 = UPDATE en transaction 'après revue manuelle des candidats' — correctif de données, pas un " +
    "audit pur. Découvert pendant l'écriture de ce garde-fou. Hors périmètre de conversion de MG.3.",
  "prisma/data-fixes/CS2-mirror-transfert-releves.sql":
    "Sprint CS.2 : création des relevés TRANSFERT miroir manquants côté vague destination. INSERT protégé " +
    "par NOT EXISTS (idempotent d'après son propre en-tête), mais reste un correctif de données à écriture, " +
    "jamais converti en migration Prisma. Découvert pendant l'écriture de ce garde-fou. Hors périmètre de " +
    "conversion de MG.3.",
  "prisma/data-fixes/GP3-cleanup-nan-gompertz.sql":
    "Daté 2026-06-16 (exécution) : nettoyage des enregistrements GompertzVague persistés avec NaN/Infinity " +
    "avant que le guard GP.2 soit en place. SECTION 1 = audit SELECT (rejouable), suivie de sections de " +
    "remédiation — correctif de données, pas un audit pur. Découvert pendant l'écriture de ce garde-fou. " +
    "Hors périmètre de conversion de MG.3.",
};

/** Répertoires racines à parcourir pour la règle (b), au sens de la mission MG.6. */
const SCAN_ROOTS = ["scripts", "prisma"];

/** Extensions concernées par la règle (b) — .sql et .sh uniquement (ADR-049/050). */
const RELEVANT_EXTENSIONS = [".sql", ".sh"];

/** Parcourt récursivement un dossier et retourne les chemins relatifs au repo. */
function listFilesRecursive(absDir: string): string[] {
  if (!existsSync(absDir)) return [];
  const out: string[] = [];
  for (const entry of readdirSync(absDir, { withFileTypes: true })) {
    const abs = path.join(absDir, entry.name);
    if (entry.isDirectory()) {
      out.push(...listFilesRecursive(abs));
    } else if (entry.isFile()) {
      out.push(path.relative(REPO_ROOT, abs));
    }
  }
  return out;
}

/**
 * Classifie un fichier .sql/.sh candidat à la règle (b). Fonction pure (ne
 * lit aucun fichier réel) — testable sur des chemins fabriqués.
 */
export function classifyDataFixCandidate(
  relPath: string
): "migration" | "audit" | "known-non-datafix" | "debt" | "violation" {
  if (isLegitimateMigrationFile(relPath)) return "migration";
  if (isQualifiedAuditPath(relPath)) return "audit";
  if (KNOWN_NON_DATAFIX_FILES.has(relPath)) return "known-non-datafix";
  if (relPath in HISTORICAL_DEBT_EXCLUSIONS) return "debt";
  return "violation";
}

describe("Garde-fou anti-recidive — correctifs de donnees hors migration (MG.6, ADR-049/ADR-050)", () => {
  describe("(a) Aucun fichier a la racine de prisma/migrations/ (cause exacte du commit c259b48)", () => {
    it("détecte un faux positif fabriqué : un .sql à la racine échoue", () => {
      const fakeEntries = [
        { name: "20260101000000_valid_migration", isFile: () => false },
        { name: "migration_lock.toml", isFile: () => true },
        { name: "fix-something-orphan.sql", isFile: () => true },
      ];
      expect(findIllegalFilesAtMigrationsRoot(fakeEntries)).toEqual(["fix-something-orphan.sql"]);
    });

    it("ne signale rien sur un ensemble d'entrées entièrement sain", () => {
      const fakeEntries = [
        { name: "20260101000000_valid_migration", isFile: () => false },
        { name: "migration_lock.toml", isFile: () => true },
      ];
      expect(findIllegalFilesAtMigrationsRoot(fakeEntries)).toEqual([]);
    });

    it("le dépôt réel ne contient aucun fichier illégitime à la racine de prisma/migrations/", () => {
      const entries = readdirSync(MIGRATIONS_DIR, { withFileTypes: true });
      const illegal = findIllegalFilesAtMigrationsRoot(entries);
      expect(
        illegal,
        `Fichier(s) illégitime(s) à la racine de prisma/migrations/ : ${illegal.join(", ")}. ` +
          `C'est exactement le bug de commit c259b48 (ADR-049 §1) : Prisma ne lit comme migration ` +
          `que les SOUS-DOSSIERS contenant un migration.sql — un fichier à la racine est inerte, ` +
          `jamais exécuté par 'migrate deploy'. Déplacer ce contenu vers ` +
          `prisma/migrations/<timestamp>_<nom>/migration.sql (idempotent, cf. ADR-049 §3.3).`
      ).toEqual([]);
    });
  });

  describe("(b) Aucun correctif de données a écriture hors du mécanisme de migration", () => {
    it("qualifie un fichier scripts/audits/*-audit-*.sql comme audit légitime", () => {
      expect(classifyDataFixCandidate("scripts/audits/foo-audit-bar.sql")).toBe("audit");
    });

    it("rejette un fichier sous scripts/audits/ SANS '-audit-' dans son nom (le dossier seul ne suffit pas)", () => {
      expect(classifyDataFixCandidate("scripts/audits/foo-bar.sql")).toBe("violation");
    });

    it("qualifie une vraie migration prisma/migrations/<dossier>/migration.sql", () => {
      expect(classifyDataFixCandidate("prisma/migrations/20260101000000_x/migration.sql")).toBe("migration");
    });

    it("qualifie un fichier compagnon (rollback.sql) dans un dossier de migration légitime", () => {
      expect(classifyDataFixCandidate("prisma/migrations/20260101000000_x/rollback.sql")).toBe("migration");
    });

    it("ne qualifie PAS un fichier plus profond qu'un dossier de migration direct (profondeur excessive)", () => {
      expect(classifyDataFixCandidate("prisma/migrations/20260101000000_x/sub/nested.sql")).toBe("violation");
    });

    it("reconnaît prisma/seed.sql comme fichier connu non-correctif", () => {
      expect(classifyDataFixCandidate("prisma/seed.sql")).toBe("known-non-datafix");
    });

    it("détecte un nouveau correctif orphelin fabriqué comme violation (cas qui doit échouer demain)", () => {
      expect(classifyDataFixCandidate("scripts/fix-nouveau-truc.sql")).toBe("violation");
      expect(classifyDataFixCandidate("prisma/data-fixes/nouveau-correctif.sql")).toBe("violation");
      expect(classifyDataFixCandidate("scripts/rattrapage.sh")).toBe("violation");
    });

    it("reconnaît la dette historique nommément listée, et seulement elle", () => {
      expect(classifyDataFixCandidate("prisma/fix-vague-26-01.sql")).toBe("debt");
      expect(classifyDataFixCandidate("scripts/repair-bug041.sql")).toBe("debt");
      // Un fichier de nom très proche mais différent n'est PAS couvert par la dette.
      expect(classifyDataFixCandidate("scripts/repair-bug042.sql")).toBe("violation");
    });

    it("stripSqlComments retire les commentaires -- et /* */ sans affecter le SQL réel", () => {
      const sql = [
        "-- ceci mentionne UPDATE et INSERT dans un commentaire, pas du code",
        "/* bloc DELETE FROM x; */",
        "SELECT 1 FROM \"Bac\";",
      ].join("\n");
      const stripped = stripSqlComments(sql);
      expect(stripped).not.toMatch(/UPDATE/);
      expect(stripped).not.toMatch(/DELETE/);
      expect(stripped).toContain('SELECT 1 FROM "Bac"');
    });

    it("le signal de cohérence détecte une écriture réelle hors commentaire (cas fautif fabriqué)", () => {
      const sqlAvecEcriture = 'UPDATE "Bac" SET "nombreActuel" = 1 WHERE id = \'x\';';
      expect(auditFileHasWriteKeywordOutsideComments(sqlAvecEcriture)).toBe(true);
    });

    it("le signal de cohérence ne se déclenche PAS sur un mot-clé mentionné seulement en commentaire", () => {
      const sqlAuditPur = [
        "-- Cet audit ne fait PAS d'UPDATE, seulement un SELECT (voir ADR-049).",
        "SELECT count(*) FROM \"AssignationBac\" WHERE \"nombrePoissons\" = 0;",
      ].join("\n");
      expect(auditFileHasWriteKeywordOutsideComments(sqlAuditPur)).toBe(false);
    });

    it("toute exclusion de dette historique a un motif écrit non vide", () => {
      for (const [file, reason] of Object.entries(HISTORICAL_DEBT_EXCLUSIONS)) {
        expect(reason.trim().length, `Exclusion sans motif : ${file}`).toBeGreaterThan(0);
      }
    });

    it("chaque fichier de la liste de dette historique existe encore dans le dépôt (la liste ne pourrit pas silencieusement)", () => {
      const missing = Object.keys(HISTORICAL_DEBT_EXCLUSIONS).filter(
        (relPath) => !existsSync(path.join(REPO_ROOT, relPath))
      );
      expect(
        missing,
        `Fichier(s) de la liste d'exclusion de dette historique introuvable(s) : ${missing.join(", ")}. ` +
          `Si ce(s) fichier(s) ont été supprimés ou convertis en migration, retirer leur entrée de ` +
          `HISTORICAL_DEBT_EXCLUSIONS dans ce test — la liste doit refléter exactement la dette réelle, ` +
          `jamais des entrées obsolètes.`
      ).toEqual([]);
    });

    it("le dépôt réel ne contient aucune violation nouvelle sous scripts/ ou prisma/ (hors dette historique tolérée)", () => {
      const candidates = SCAN_ROOTS.flatMap((root) => listFilesRecursive(path.join(REPO_ROOT, root))).filter(
        (relPath) => RELEVANT_EXTENSIONS.includes(path.extname(relPath))
      );

      const violations = candidates.filter(
        (relPath) => classifyDataFixCandidate(relPath) === "violation"
      );

      expect(
        violations,
        `Correctif(s) de données détecté(s) hors du mécanisme de migration : ${violations.join(", ")}. ` +
          `ADR-049 : tout correctif de données (toute opération qui modifie des lignes existantes) doit ` +
          `être une migration Prisma versionnée — créer manuellement ` +
          `prisma/migrations/<timestamp>_<nom>/migration.sql (idempotent : valeur cible absolue, jamais ` +
          `un delta relatif ; no-op silencieux si la ligne visée est absente ; journalisé via RAISE NOTICE ; ` +
          `protégé par un garde-fou de précondition qui échoue AVANT toute écriture — voir ADR-049 §3.3). ` +
          `Si ce fichier est réellement un audit en lecture seule (zéro écriture, sans exception), le placer ` +
          `sous scripts/audits/ avec '-audit-' dans son nom (ADR-050) plutôt que de l'ajouter à la liste de ` +
          `dette historique de ce test.`
      ).toEqual([]);
    });

    it("les fichiers .sql sous scripts/audits/ ne contiennent aucun mot-clé d'écriture hors commentaire (signal de cohérence)", () => {
      const auditSqlFiles = listFilesRecursive(path.join(REPO_ROOT, "scripts/audits")).filter(
        (relPath) => path.extname(relPath) === ".sql"
      );
      expect(auditSqlFiles.length, "Aucun fichier .sql trouvé sous scripts/audits/ — l'assertion suivante serait vide de sens").toBeGreaterThan(0);

      const inconsistent = auditSqlFiles.filter((relPath) => {
        const content = readFileSync(path.join(REPO_ROOT, relPath), "utf-8");
        return auditFileHasWriteKeywordOutsideComments(content);
      });

      expect(
        inconsistent,
        `Fichier(s) sous scripts/audits/ qualifié(s) "audit" par nommage mais contenant un mot-clé ` +
          `d'écriture SQL hors commentaire : ${inconsistent.join(", ")}. Un audit doit être strictement ` +
          `en lecture seule (ADR-049 §3.1, critère "zéro écriture, sans exception") — vérifier s'il s'agit ` +
          `en réalité d'un correctif de données déguisé.`
      ).toEqual([]);
    });
  });
});
