/**
 * Barrel export — point d'entree unique pour tous les types du projet.
 *
 * Usage :
 * ```ts
 * import { Bac, CreateVagueDTO, IndicateursVague, ReleveTyped } from "@/types";
 * ```
 */

// Modeles et enums Prisma
export {
  Role,
  Permission,
  StatutVague,
  TypeReleve,
  TypeAliment,
  CauseMortalite,
  MethodeComptage,
  CategorieProduit,
  UniteStock,
  TypeMouvement,
  StatutCommande,
  StatutFacture,
  ModePaiement,
  SexeReproducteur,
  StatutReproducteur,
  StatutPonte,
  StatutLotAlevins,
  // Sprint 11 — Alertes & Planning
  TypeAlerte,
  StatutAlerte,
  TypeActivite,
  StatutActivite,
  Recurrence,
} from "./models";
export type {
  Site,
  SiteRole,
  SiteRoleWithCount,
  SiteMember,
  SiteMemberWithRelations,
  SiteWithMembers,
  User,
  Session,
  SessionWithUser,
  Bac,
  BacWithVague,
  Vague,
  VagueWithRelations,
  Releve,
  ReleveWithRelations,
  Fournisseur,
  Produit,
  ProduitWithFournisseur,
  MouvementStock,
  MouvementStockWithRelations,
  Commande,
  CommandeWithRelations,
  LigneCommande,
  LigneCommandeWithProduit,
  ReleveConsommation,
  ReleveConsommationWithRelations,
  Client,
  Vente,
  VenteWithRelations,
  Facture,
  FactureWithRelations,
  Paiement,
  PaiementWithRelations,
  Reproducteur,
  ReproducteurWithRelations,
  Ponte,
  PonteWithRelations,
  LotAlevins,
  LotAlevinsWithRelations,
  // Sprint 11 — Alertes & Planning
  ConfigAlerte,
  ConfigAlerteWithRelations,
  Notification,
  NotificationWithRelations,
  Activite,
  ActiviteWithRelations,
} from "./models";

// Types authentification et multi-tenancy (DTOs, session, contexte)
export type {
  UserSession,
  AuthContext,
  LoginDTO,
  RegisterDTO,
  CreateSiteDTO,
  UpdateSiteDTO,
  SwitchSiteDTO,
  AddMemberDTO,
  UpdateMemberDTO,
  CreateSiteRoleDTO,
  UpdateSiteRoleDTO,
  AuthResponse,
} from "./auth";

// Types discrimines pour les releves
export type {
  ReleveBase,
  ReleveBiometrie,
  ReleveMortalite,
  ReleveAlimentation,
  ReleveQualiteEau,
  ReleveComptage,
  ReleveObservation,
  ReleveTyped,
} from "./releves";
export {
  isBiometrie,
  isMortalite,
  isAlimentation,
  isQualiteEau,
  isComptage,
  isObservation,
} from "./releves";

// DTOs API
export type {
  CreateBacDTO,
  UpdateBacDTO,
  BacResponse,
  BacListResponse,
  CreateVagueDTO,
  UpdateVagueDTO,
  VagueSummaryResponse,
  VagueListResponse,
  VagueDetailResponse,
  CreateReleveBiometrieDTO,
  CreateReleveMortaliteDTO,
  CreateReleveAlimentationDTO,
  CreateReleveQualiteEauDTO,
  CreateReleveComptageDTO,
  CreateReleveObservationDTO,
  CreateReleveConsommationDTO,
  CreateReleveDTO,
  UpdateReleveDTO,
  ReleveFilters,
  ReleveListResponse,
  CreateFournisseurDTO,
  UpdateFournisseurDTO,
  FournisseurListResponse,
  CreateProduitDTO,
  UpdateProduitDTO,
  ProduitFilters,
  ProduitListResponse,
  CreateMouvementDTO,
  MouvementFilters,
  MouvementListResponse,
  CreateLigneCommandeDTO,
  CreateCommandeDTO,
  UpdateCommandeDTO,
  CommandeFilters,
  CommandeListResponse,
  CommandeDetailResponse,
  CreateClientDTO,
  UpdateClientDTO,
  ClientListResponse,
  CreateVenteDTO,
  VenteListResponse,
  VenteFilters,
  CreateFactureDTO,
  UpdateFactureDTO,
  FactureFilters,
  FactureListResponse,
  FactureDetailResponse,
  CreatePaiementDTO,
  PaiementListResponse,
  CreateReproducteurDTO,
  UpdateReproducteurDTO,
  ReproducteurFilters,
  ReproducteurListResponse,
  CreatePonteDTO,
  UpdatePonteDTO,
  PonteFilters,
  PonteListResponse,
  CreateLotAlevinsDTO,
  UpdateLotAlevinsDTO,
  TransfertLotDTO,
  LotAlevinsFilters,
  LotAlevinsListResponse,
  ApiError,
  ValidationErrorResponse,
  // Sprint 11 — Alertes, Planning, Finances
  CreateConfigAlerteDTO,
  UpdateConfigAlerteDTO,
  UpdateNotificationDTO,
  CompleteActiviteDTO,
  CreateActiviteDTO,
  UpdateActiviteDTO,
  ActiviteFilters,
  FinancesPeriode,
} from "./api";
// Sprint 13 — Liaison Planning ↔ Relevés
export { ACTIVITE_RELEVE_TYPE_MAP } from "./api";
// Sprint 14 — Completion types
export { RELEVE_COMPATIBLE_TYPES } from "./api";

// Types pour les calculs et indicateurs
export type {
  IndicateursVague,
  BilanVague,
  EvolutionPoidsPoint,
  EvolutionMortalitePoint,
  AlimentationPoint,
  DashboardData,
  VagueDashboardSummary,
  IndicateursBac,
  ComparaisonBacs,
  AlerteBac,
  HistoriqueBac,
  HistoriqueBacCycle,
  AnalytiqueAliment,
  ComparaisonAliments,
  DetailAliment,
  DetailAlimentVague,
  SimulationResult,
  // CR-012 — Analytics dashboard + comparaison vagues
  TendanceFCRPoint,
  AnalyticsDashboard,
  IndicateursVagueComplet,
  ComparaisonVagues,
} from "./calculs";

// Types export PDF/Excel — Sprint 12
export type {
  SiteInfoExport,
  PeriodeExport,
  ClientFacturePDF,
  PaiementFacturePDF,
  CreateFacturePDFDTO,
  KPIsVaguePDF,
  BacRapportPDF,
  ReleveRapportPDF,
  EvolutionPoidsExport,
  CreateRapportVaguePDFDTO,
  KPIsFinanciersPDF,
  VenteParVaguePDF,
  TopClientPDF,
  EvolutionMensuellePDF,
  CreateRapportFinancierPDFDTO,
  ReleveExcelRow,
  ExportRelevesExcelDTO,
  MouvementExcelRow,
  ExportStockExcelDTO,
  VenteExcelRow,
  ExportVentesExcelDTO,
} from "./export";
