-- Migration Sprint 34 — Ajouter COMMISSION_PREMIUM à l'enum Permission
-- Approche RECREATE pour éviter ERR-001 (ADD VALUE + UPDATE dans la même transaction)

-- Étape 1 : Renommer l'ancien enum
ALTER TYPE "Permission" RENAME TO "Permission_old";

-- Étape 2 : Créer le nouvel enum avec COMMISSION_PREMIUM
CREATE TYPE "Permission" AS ENUM (
  'SITE_GERER',
  'MEMBRES_GERER',
  'VAGUES_VOIR',
  'VAGUES_CREER',
  'VAGUES_MODIFIER',
  'BACS_GERER',
  'BACS_MODIFIER',
  'RELEVES_VOIR',
  'RELEVES_CREER',
  'RELEVES_MODIFIER',
  'STOCK_VOIR',
  'STOCK_GERER',
  'APPROVISIONNEMENT_VOIR',
  'APPROVISIONNEMENT_GERER',
  'CLIENTS_VOIR',
  'CLIENTS_GERER',
  'VENTES_VOIR',
  'VENTES_CREER',
  'FACTURES_VOIR',
  'FACTURES_GERER',
  'PAIEMENTS_CREER',
  'ALEVINS_VOIR',
  'ALEVINS_GERER',
  'ALEVINS_CREER',
  'ALEVINS_MODIFIER',
  'ALEVINS_SUPPRIMER',
  'PLANNING_VOIR',
  'PLANNING_GERER',
  'FINANCES_VOIR',
  'FINANCES_GERER',
  'DASHBOARD_VOIR',
  'ALERTES_VOIR',
  'EXPORT_DONNEES',
  'ALERTES_CONFIGURER',
  'DEPENSES_VOIR',
  'DEPENSES_CREER',
  'DEPENSES_PAYER',
  'BESOINS_SOUMETTRE',
  'BESOINS_APPROUVER',
  'BESOINS_TRAITER',
  'GERER_PACKS',
  'ACTIVER_PACKS',
  'GERER_CONFIG_ELEVAGE',
  'REGLES_ACTIVITES_VOIR',
  'GERER_REGLES_ACTIVITES',
  'MONITORING_CLIENTS',
  'ENVOYER_NOTES',
  'CALIBRAGES_VOIR',
  'CALIBRAGES_CREER',
  'CALIBRAGES_MODIFIER',
  'GERER_REGLES_GLOBALES',
  'UTILISATEURS_VOIR',
  'UTILISATEURS_CREER',
  'UTILISATEURS_MODIFIER',
  'UTILISATEURS_SUPPRIMER',
  'UTILISATEURS_GERER',
  'UTILISATEURS_IMPERSONNER',
  'ABONNEMENTS_VOIR',
  'ABONNEMENTS_GERER',
  'PLANS_GERER',
  'REMISES_GERER',
  'COMMISSIONS_VOIR',
  'COMMISSIONS_GERER',
  'COMMISSION_PREMIUM',
  'PORTEFEUILLE_VOIR',
  'PORTEFEUILLE_GERER'
);

-- Étape 3 : Migrer les colonnes qui utilisent cet enum
-- SiteRole.permissions (Permission[])
ALTER TABLE "SiteRole" ALTER COLUMN "permissions" TYPE "Permission"[] USING "permissions"::text::"Permission"[];

-- Étape 4 : Supprimer l'ancien enum
DROP TYPE "Permission_old";
